apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: cicd
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32000
  - name: agent
    port: 50000
    targetPort: 50000  
